name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-debug:
    name: macOS (Debug)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Run tests (debug)
        run: swift test -c debug

  macos-release:
    name: macOS (Release)
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build (release)
        run: swift build -c release

      - name: Run tests (release)
        run: swift test -c release

  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        run: swift test

  readme-validation:
    name: README Validation
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Run README verification tests
        run: swift test --filter ReadmeVerificationTests
