name: SwiftLint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        continue-on-error: true
