name: SwiftLint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict
        continue-on-error: true
